### ISSUE TITLE
ParserError: ChannelNamePart3Message needs exactly one bit set in channel byte

### ISSUE THREAD

**Issue by dverhelst** [Cereal2nd/velbus-aio#73]
Error during initial startup/scan.

```
2022-12-06 10:59:59.291 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/velbusaio/protocol.py", line 169, in _process_message
    await self._message_received_callback(msg)
  File "/usr/local/lib/python3.10/site-packages/velbusaio/controller.py", line 55, in _on_message_received
    await self._handler.handle(msg)
  File "/usr/local/lib/python3.10/site-packages/velbusaio/handler.py", line 93, in handle
    msg.populate(priority, address, rtr, data)
  File "/usr/local/lib/python3.10/site-packages/velbusaio/messages/channel_name_part3.py", line 35, in populate
    self.needs_one_channel(channels)
  File "/usr/local/lib/python3.10/site-packages/velbusaio/message.py", line 235, in needs_one_channel
    self.parser_error("needs exactly one bit set in channel byte")
  File "/usr/local/lib/python3.10/site-packages/velbusaio/message.py", line 134, in parser_error
    raise ParserError(self.__class__.__name__ + " " + message)
velbusaio.message.ParserError: ChannelNamePart3Message needs exactly one bit set in channel byte
2022-12-06 10:59:59.385 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/velbusaio/protocol.py", line 169, in _process_message
    await self._message_received_callback(msg)
  File "/usr/local/lib/python3.10/site-packages/velbusaio/controller.py", line 55, in _on_message_received
    await self._handler.handle(msg)
  File "/usr/local/lib/python3.10/site-packages/velbusaio/handler.py", line 93, in handle
    msg.populate(priority, address, rtr, data) 
  File "/usr/local/lib/python3.10/site-packages/velbusaio/messages/channel_name_part3.py", line 35, in populate 
    self.needs_one_channel(channels)
  File "/usr/local/lib/python3.10/site-packages/velbusaio/message.py", line 235, in needs_one_channel 
    self.parser_error("needs exactly one bit set in channel byte")
  File "/usr/local/lib/python3.10/site-packages/velbusaio/message.py", line 134, in parser_error
    raise ParserError(self.__class__.__name__ + " " + message)
velbusaio.message.ParserError: ChannelNamePart3Message needs exactly one bit set in channel byte                                                                                                                            
```

Using latest release 2022.11.5 of HomeAssistant

Anything else you require?

**Comment by Cereal2nd** [comment]
what module is this?

**Comment by dverhelst** [comment]
@Cereal2nd . seems to happen on the VMBGP4PIR modules, so possibly related to #72  ?

```
2022-12-06 11:50:45.812 DEBUG (MainThread) [velbus-packet] Received {"name": "ModuleStatusMessage", "priority": 251, "address": 224, "rtr": false, "data": "", "closed": [5, 8], "led_on": [1, 2, 3, 4, 5, 6], "led_slow_blinking": [1, 2, 3, 4, 5, 6, 7, 8], "led_fast_blinking": []}
2022-12-06 11:50:45.827 DEBUG (MainThread) [velbus-protocol] RX: RawMessage(priority=fb, address=e0, rtr=False, command=234, data=b'ea 00 00 00 2e 0a 00 00')
2022-12-06 11:50:45.828 DEBUG (MainThread) [velbus-packet] Received {"name": "TempSensorStatusMessage", "priority": 251, "address": 224, "rtr": false, "data": "", "local_control": 0, "status_mode": "run", "status_str": "run", "auto_send": 0, "mode": "safe", "mode_str": "safe", "cool": 0, "heater": 0, "boost": 0, "pump": 0, "alarm1": 0, "alarm2": 0, "alarm3": 0, "alarm4": 0, "current_temp": 23.0, "target_temp": 5.0, "sleep_timer": 0, "_status_str": "run"}
2022-12-06 11:50:45.848 DEBUG (MainThread) [velbus-protocol] TX: RawMessage(priority=fb, address=e0, rtr=False, command=239, data=b'ef ff')
2022-12-06 11:50:45.874 DEBUG (MainThread) [velbus-protocol] RX: RawMessage(priority=fb, address=e0, rtr=False, command=240, data=b'f0 01 50 75 73 68 20 62')
2022-12-06 11:50:45.874 DEBUG (MainThread) [velbus-packet] Received {"name": "Push b", "priority": 251, "address": 224, "rtr": false, "data": "", "channel": 1}
2022-12-06 11:50:45.915 DEBUG (MainThread) [velbus-protocol] RX: RawMessage(priority=fb, address=e0, rtr=False, command=241, data=b'f1 01 75 74 74 6f 6e 20')
2022-12-06 11:50:45.915 DEBUG (MainThread) [velbus-packet] Received {"name": "utton ", "priority": 251, "address": 224, "rtr": false, "data": "", "channel": 1}
2022-12-06 11:50:45.921 DEBUG (MainThread) [velbus-protocol] RX: RawMessage(priority=fb, address=e0, rtr=False, command=242, data=b'f2 01 31 ff ff ff')
2022-12-06 11:50:45.922 DEBUG (MainThread) [velbus-packet] Received {"name": "1\u00ff\u00ff\u00ff", "priority": 251, "address": 224, "rtr": false, "data": "", "channel": 1}
2022-12-06 11:50:45.927 DEBUG (MainThread) [velbus-protocol] RX: RawMessage(priority=fb, address=e0, rtr=False, command=240, data=b'f0 02 50 75 73 68 20 62')
2022-12-06 11:50:45.928 DEBUG (MainThread) [velbus-packet] Received {"name": "Push b", "priority": 251, "address": 224, "rtr": false, "data": "", "channel": 2}
2022-12-06 11:50:45.937 DEBUG (MainThread) [velbus-protocol] RX: RawMessage(priority=fb, address=e0, rtr=False, command=241, data=b'f1 02 75 74 74 6f 6e 20')
2022-12-06 11:50:45.937 DEBUG (MainThread) [velbus-packet] Received {"name": "utton ", "priority": 251, "address": 224, "rtr": false, "data": "", "channel": 2}
2022-12-06 11:50:45.950 DEBUG (MainThread) [velbus-protocol] RX: RawMessage(priority=fb, address=e0, rtr=False, command=242, data=b'f2 02 32 ff ff ff')
2022-12-06 11:50:45.951 DEBUG (MainThread) [velbus-packet] Received {"name": "2\u00ff\u00ff\u00ff", "priority": 251, "address": 224, "rtr": false, "data": "", "channel": 2}
2022-12-06 11:50:45.967 DEBUG (MainThread) [velbus-protocol] RX: RawMessage(priority=fb, address=e0, rtr=False, command=240, data=b'f0 03 50 75 73 68 20 62')
2022-12-06 11:50:45.968 DEBUG (MainThread) [velbus-packet] Received {"name": "Push b", "priority": 251, "address": 224, "rtr": false, "data": "", "channel": 3}
2022-12-06 11:50:45.987 DEBUG (MainThread) [velbus-protocol] RX: RawMessage(priority=fb, address=e0, rtr=False, command=241, data=b'f1 03 75 74 74 6f 6e 20')
2022-12-06 11:50:45.988 DEBUG (MainThread) [velbus-packet] Received {"name": "utton ", "priority": 251, "address": 224, "rtr": false, "data": "", "channel": 3}
2022-12-06 11:50:46.000 DEBUG (MainThread) [velbus-protocol] RX: RawMessage(priority=fb, address=e0, rtr=False, command=242, data=b'f2 03 33 ff ff ff')
2022-12-06 11:50:46.000 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/velbusaio/protocol.py", line 169, in _process_message
    await self._message_received_callback(msg)
  File "/usr/local/lib/python3.10/site-packages/velbusaio/controller.py", line 55, in _on_message_received
    await self._handler.handle(msg)
  File "/usr/local/lib/python3.10/site-packages/velbusaio/handler.py", line 93, in handle
    msg.populate(priority, address, rtr, data)
  File "/usr/local/lib/python3.10/site-packages/velbusaio/messages/channel_name_part3.py", line 35, in populate
    self.needs_one_channel(channels)
  File "/usr/local/lib/python3.10/site-packages/velbusaio/message.py", line 235, in needs_one_channel
    self.parser_error("needs exactly one bit set in channel byte")
  File "/usr/local/lib/python3.10/site-packages/velbusaio/message.py", line 134, in parser_error
    raise ParserError(self.__class__.__name__ + " " + message)
velbusaio.message.ParserError: ChannelNamePart3Message needs exactly one bit set in channel byte
```

**Comment by Cereal2nd** [comment]
this was already handled in #66 but this is not yet in HA

**Comment by dverhelst** [comment]
Great!
When is it expected to be in HA? In 2022.12 ?

**Comment by Cereal2nd** [comment]
probably the first release of 23

**Comment by dverhelst** [comment]
It will be worth the wait!
Thanks for keeping this integration really good @Cereal2nd !

**Comment by dverhelst** [comment]
Confirmed ok!
